"""
Django settings for AbbaRestaurante project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from urllib.parse import urlparse, urlunparse, parse_qs, urlencode
from pathlib import Path
import pusher
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- Configuración de Entorno (Desarrollo local vs Render producción) ---

# Detectar si estamos en producción en Render
IS_RENDER = 'RENDER' in os.environ

# SECURITY WARNING: don't run with debug turned on in production!
# En producción, DEBUG debe ser False.
DEBUG = os.environ.get('DEBUG', 'True') == 'True' and not IS_RENDER

# SECURITY WARNING: keep the secret key used in production secret!
# La SECRET_KEY se leerá desde las variables de entorno en producción
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-9q340snr7*@mbs+7z06vv=pq0j#voi*%&+hvw1l+8wn!90$i@p'
    else:
        raise ValueError("SECRET_KEY environment variable must be set in production")

if DEBUG:
    # En desarrollo, permitimos cualquier host para mayor flexibilidad.
    ALLOWED_HOSTS = ['*']
    SITE_URL = 'http://localhost:8000'
else:
    # En producción en Render
    render_domain = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
    ALLOWED_HOSTS = [render_domain] if render_domain else ['*']
    CSRF_TRUSTED_ORIGINS = [f'https://{render_domain}'] if render_domain else []
    SITE_URL = f'https://{render_domain}' if render_domain else 'https://abbarestaurante.onrender.com'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'restaurant.apps.RestaurantConfig',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'AbbaRestaurante.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'AbbaRestaurante.context_processors.export_settings',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Configuración de la base de datos para desarrollo y producción

if DEBUG:
    # Configuración para desarrollo local (MySQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'abbarestaurante'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
        }
    }
else:
    # Configuración para producción (Render)
    DATABASE_URL = os.environ.get('DATABASE_URL')
    
    if not DATABASE_URL:
        raise ValueError("DATABASE_URL environment variable must be set in production")

    DATABASES = {'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)}



STATIC_URL = '/static/'


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración de WhiteNoise para servir archivos estáticos en producción
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/restaurant/'
LOGOUT_REDIRECT_URL = '/restaurant/'

# Media files configuration for user uploads (images, etc.)
# Usar almacenamiento local, Cloudinary se usa directamente en el código
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# PUSHER CONFIGURATION
PUSHER_APP_ID = os.environ.get('PUSHER_APP_ID', '')
PUSHER_KEY = os.environ.get('PUSHER_KEY', '')
PUSHER_SECRET = os.environ.get('PUSHER_SECRET', '')
PUSHER_CLUSTER = os.environ.get('PUSHER_CLUSTER', '')

# Instancia del cliente Pusher para ser usada en las vistas
# En producción, ssl=True es crucial para usar wss://
PUSHER_SSL = not DEBUG

# Solo crear cliente Pusher si todas las variables están configuradas
pusher_client = None
if all([PUSHER_APP_ID, PUSHER_KEY, PUSHER_SECRET, PUSHER_CLUSTER]):
    pusher_client = pusher.Pusher(
      app_id=PUSHER_APP_ID,
      key=PUSHER_KEY,
      secret=PUSHER_SECRET,
      cluster=PUSHER_CLUSTER,
      ssl=PUSHER_SSL
    )

# Cloudinary Configuration for Cloud Storage
cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', 'dvjcrc3ei'),
    api_key=os.environ.get('CLOUDINARY_API_KEY', '638756761769688'),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET', 'dnD4bo63Fi7PSvbo2MYqoF4q00U')
)

# Cloudinary Storage Settings
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', 'dvjcrc3ei'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', '638756761769688'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', 'dnD4bo63Fi7PSvbo2MYqoF4q00U'),
}

# Use Cloudinary for media file storage in production AND development (for consistency)
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
