"""
Django settings for AbbaRestaurante project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from urllib.parse import urlparse, urlunparse, parse_qs, urlencode
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La SECRET_KEY se leerá desde las variables de entorno en producción
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-9q340snr7*@mbs+7z06vv=pq0j#voi*%&+hvw1l+8wn!90$i@p')

# SECURITY WARNING: don't run with debug turned on in production!
# En producción, DEBUG debe ser False. La variable de entorno 'DEBUG' no estará presente en Koyeb.
DEBUG = os.environ.get('DEBUG', 'True') == 'True' # Por defecto es True para desarrollo local

if DEBUG:
    # En desarrollo, permitimos cualquier host para mayor flexibilidad.
    ALLOWED_HOSTS = ['*']
else:
    # En producción, solo permitimos el dominio específico de Koyeb.
    koyeb_domain = os.environ.get('KOYEB_PUBLIC_DOMAIN')
    ALLOWED_HOSTS = [koyeb_domain] if koyeb_domain else []
    
    # Es crucial decirle a Django que confíe en este dominio para peticiones POST seguras (HTTPS).
    CSRF_TRUSTED_ORIGINS = [f'https://{koyeb_domain}'] if koyeb_domain else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'restaurant.apps.RestaurantConfig',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'AbbaRestaurante.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'AbbaRestaurante.context_processors.export_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'AbbaRestaurante.wsgi.application'
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Configuración de la base de datos para desarrollo y producción
if DEBUG:
    # Configuración para desarrollo local (MySQL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'abbarestaurante_db',
            'USER': 'root',
            'PASSWORD': 'root',
            'HOST': 'localhost',
            'PORT': '3306',
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    # Configuración para producción (Koyeb - Neon PostgreSQL)
    DATABASE_URL = os.environ.get('DATABASE_URL', None)
    if not DATABASE_URL:
        raise ValueError("La variable de entorno DATABASE_URL no está configurada en producción.")

    # El parámetro 'channel_binding' de Neon no es compatible con psycopg2.
    # Lo eliminamos de la URL de forma segura antes de que Django la use.
    url_parts = urlparse(DATABASE_URL)
    query_params = parse_qs(url_parts.query)
    query_params.pop('channel_binding', None)  # Elimina la clave si existe
    new_query = urlencode(query_params, doseq=True)
    safe_database_url = urlunparse(url_parts._replace(query=new_query))

    DATABASES = {'default': dj_database_url.parse(safe_database_url, conn_max_age=600)}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# La advertencia W004 indica que esta carpeta no existe. La comentamos para limpiar el log.
# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]
# Configuración de WhiteNoise para servir archivos estáticos en producción
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/restaurant/'
LOGOUT_REDIRECT_URL = '/restaurant/'

# PUSHER CONFIGURATION
PUSHER_APP_ID = os.environ.get('PUSHER_APP_ID', '')
PUSHER_KEY = os.environ.get('PUSHER_KEY', '')
PUSHER_SECRET = os.environ.get('PUSHER_SECRET', '')
PUSHER_CLUSTER = os.environ.get('PUSHER_CLUSTER', '')
