# Generated by Django 5.2.7 on 2025-10-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('paid', 'Paid'), ('charged_to_room', 'Cargado a Habitación'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
