# Generated by Django 5.2.7 on 2025-11-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_prepared',
            field=models.BooleanField(default=False, help_text='Marca si este item ya fue preparado/completado'),
        ),
    ]
