# Generated by Django 5.2.7 on 2025-11-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_orderitem_is_prepared'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
