# Generated by Django 5.2.7
# This migration renames all models to Spanish names

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_category_add'),
    ]

    operations = [
        # Rename old models to Spanish
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='ArticuloMenu',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Pedido',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ItemPedido',
        ),
        migrations.RenameModel(
            old_name='RegistrationPin',
            new_name='PinRegistro',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        # Rename the category field in ArticuloMenu
        migrations.RenameField(
            model_name='articulomenu',
            old_name='category',
            new_name='categoria',
        ),
        # Rename ForeignKey fields in ItemPedido
        migrations.RenameField(
            model_name='itempedido',
            old_name='order',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='menu_item',
            new_name='articulo_menu',
        ),
    ]
