# Generated by Django 5.2.7
# This migration renames all tables and fields using SQL, then updates Django's state

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_category_add'),
    ]

    operations = [
        # First, rename tables in the database using SQL
        migrations.RunSQL(
            sql=[
                "ALTER TABLE restaurant_menuitem RENAME TO restaurant_articulomenu;",
                "ALTER TABLE restaurant_order RENAME TO restaurant_pedido;",
                "ALTER TABLE restaurant_orderitem RENAME TO restaurant_itempedido;",
                "ALTER TABLE restaurant_registrationpin RENAME TO restaurant_pinregistro;",
                "ALTER TABLE restaurant_category RENAME TO restaurant_categoria;",
            ],
            reverse_sql=[
                "ALTER TABLE restaurant_categoria RENAME TO restaurant_category;",
                "ALTER TABLE restaurant_pinregistro RENAME TO restaurant_registrationpin;",
                "ALTER TABLE restaurant_itempedido RENAME TO restaurant_orderitem;",
                "ALTER TABLE restaurant_pedido RENAME TO restaurant_order;",
                "ALTER TABLE restaurant_articulomenu RENAME TO restaurant_menuitem;",
            ]
        ),
        # Rename field columns
        migrations.RunSQL(
            sql=[
                "ALTER TABLE restaurant_articulomenu RENAME COLUMN category TO categoria;",
                "ALTER TABLE restaurant_itempedido RENAME COLUMN order_id TO pedido_id;",
                "ALTER TABLE restaurant_itempedido RENAME COLUMN menu_item_id TO articulo_menu_id;",
            ],
            reverse_sql=[
                "ALTER TABLE restaurant_itempedido RENAME COLUMN articulo_menu_id TO menu_item_id;",
                "ALTER TABLE restaurant_itempedido RENAME COLUMN pedido_id TO order_id;",
                "ALTER TABLE restaurant_articulomenu RENAME COLUMN categoria TO category;",
            ]
        ),
        # Now update Django's internal state to match
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='ArticuloMenu',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='Pedido',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ItemPedido',
        ),
        migrations.RenameModel(
            old_name='RegistrationPin',
            new_name='PinRegistro',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        # Update field names in the state
        migrations.RenameField(
            model_name='articulomenu',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='order',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='menu_item',
            new_name='articulo_menu',
        ),
    ]
