# Generated by Django 5.2.7 on 2025-12-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_rename_all_models_to_spanish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulomenu',
            options={'verbose_name': 'Artículo de Menú', 'verbose_name_plural': 'Artículos de Menú'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Items de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pinregistro',
            options={'verbose_name': 'PIN de Registro', 'verbose_name_plural': 'PINs de Registro'},
        ),
    ]
