# Generated by Django 5.2.7 on 2025-12-10 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurant', '0009_rename_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='registrationpin',
            options={'verbose_name': 'Registration PIN', 'verbose_name_plural': 'Registration PINs'},
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('mixed', 'Mixto')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_identifier',
            field=models.CharField(blank=True, help_text="Client identifier (e.g., 'Bar 1', 'John Doe')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='room_number',
            field=models.CharField(blank=True, help_text='Guest room number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'En preparación'), ('ready', 'Listo'), ('served', 'Servido'), ('paid', 'Pagado'), ('charged_to_room', 'Cargado a Habitación'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_prepared',
            field=models.BooleanField(default=False, help_text='Mark if this item has been prepared/completed'),
        ),
        migrations.AlterField(
            model_name='registrationpin',
            name='group',
            field=models.ForeignKey(help_text='The role to be assigned to the user.', on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='registrationpin',
            name='pin',
            field=models.CharField(help_text='10-character registration PIN.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationpin',
            name='used_by',
            field=models.OneToOneField(blank=True, help_text='User who used this PIN.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Número telefónico', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_visits', models.IntegerField(default=0, help_text='Cantidad total de visitas')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Total gastado', max_digits=12)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('discount_percentage', models.IntegerField(default=0, help_text='Descuento en porcentaje')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre preferencias del cliente', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-last_visit', '-total_visits'],
                'indexes': [models.Index(fields=['phone'], name='restaurant__phone_75015e_idx'), models.Index(fields=['email'], name='restaurant__email_6932e7_idx'), models.Index(fields=['-last_visit'], name='restaurant__last_vi_cfa7a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Número de habitación', max_length=10, unique=True)),
                ('capacity', models.IntegerField(default=2, help_text='Capacidad de huéspedes')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('pending_payment', 'Pago Pendiente'), ('cleaning', 'Limpieza')], default='available', max_length=20)),
                ('total_consumption', models.DecimalField(decimal_places=2, default=0.0, help_text='Total de consumo de la sesión actual', max_digits=12)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('expected_checkout', models.DateTimeField(blank=True, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_order', models.ForeignKey(blank=True, help_text='Pedido actual de la habitación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='restaurant.order')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RoomConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(help_text='Descripción del consumo', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_history', to='restaurant.room')),
            ],
            options={
                'verbose_name': 'Room Consumption',
                'verbose_name_plural': 'Room Consumptions',
                'ordering': ['-consumption_date'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='restaurant__status_681e18_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['number'], name='restaurant__number_14c760_idx'),
        ),
        migrations.AddIndex(
            model_name='roomconsumption',
            index=models.Index(fields=['room', 'consumption_date'], name='restaurant__room_id_4cb2c5_idx'),
        ),
    ]
